site/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('root');

Route::get('/excursion', function () {
    return view('excursion');
})->name('excursion');

Route::get('/menu', function () {
    return view('menu');
})->name('menu');

Route::get('stocks/list','StockController@list')->name('stocks.list');
Route::resource('stocks', 'StockController');
Route::get('equipement/list','EquipementController@list')->name('equipement.list');
Route::resource('equipement', 'EquipementController');
Route::get('tableau-de-bord', 'TableauDeBordController@afficher')->name('tableau-de-bord');
Route::resource('tasks', 'TasksController');
Route::resource('todo-list', 'TodoListController');
Route::resource('types', 'TypeController');
Route::resource('planning', 'PlanningController');
Route::resource('data','DataController');

Route::get('/home', 'HomeController@index')->name('home');

site/resources/views/base.blade.php
t<!DOCTYPE html>

<html lang="french">
<head>
      <meta charset="utf-8">
      <link href="./css/app.css" rel="stylesheet" />
      <title>Futurexplor</title>
</head>

<body>
      <header>
            @section('header')
            <p>Header</p>
            @show
      </header>
      @section('content')
      <div class="container">
            <div class="row">
                  <div class="col-2">
            <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec non orci in odio porttitor ultrices. Integer porta tincidunt ipsum in suscipit. Sed risus velit, rhoncus accumsan interdum id, rhoncus sed ipsum. Nulla id egestas augue, et aliquet nibh. Mauris felis mi, vestibulum id sagittis at, accumsan eu nisi. Donec nisl eros, suscipit eu ante in, finibus tristique sem. Curabitur dui neque, porta ac rhoncus sit amet, faucibus vel lacus. Aenean non libero lectus. Duis vehicula metus ut ultricies viverra.
            </p>
                  </div>

                  <div class="col-6">
            <p>

                  Nam quis sapien a dolor gravida viverra in ut arcu. Ut placerat gravida metus sed commodo. Vivamus venenatis, velit malesuada tristique elementum, velit purus vehicula tortor, in lobortis leo tellus id dolor. Praesent semper sapien ultricies, auctor tortor id, tempus arcu. Curabitur pretium, mauris vel consequat molestie, nibh ipsum sagittis velit, eget fringilla erat arcu eu turpis. Quisque volutpat ex sit amet tellus bibendum, non semper lectus lobortis. Quisque nec vulputate massa.
            </p>
      </div>
<div class="col">
            <p>
                  Sed odio sem, molestie eu turpis vitae, lobortis volutpat lectus. Suspendisse potenti. Donec vel urna eget dolor tempor laoreet sit amet sit amet quam. Aliquam a mollis enim, ut tincidunt nulla. Duis porta molestie eros eu cursus. Morbi gravida in eros vitae consequat. In in pretium ipsum. Proin quis metus nec diam lacinia tincidunt eget sit amet velit.
            </p>
      </div>
      </div>
@show
      <footer>

      </footer>

</body>
</html>

site/resources/views/default.blade.php
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="favicon.ico">

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>@yield('title')</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
          crossorigin="" />
    <link href="/css/nav.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/app.css" rel="stylesheet">
    <link href="/css/StyleHome.css" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{{route('root')}}">Survival</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
             <li class="nav-item active dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Stocks</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{{route('stocks.index')}}">Gestion stocks</a>
                  <a class="dropdown-item" href="{{route('types.index')}}">Gestion types</a>
                  <a class="dropdown-item" href="{{route('equipement.index')}}">Gestion équipement</a>
                </div>
              </li>
            <li class="nav-item active dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Todo list</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{{route('todo-list.index')}}">Gestion Todo-list</a>
                  <a class="dropdown-item" href="{{route('tasks.index')}}">Gestion tâches</a>
                </div>
              </li>
            <li class="nav-item active dropdown">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Planning</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{{route('planning.index')}}">Gestion Planning</a>
                </div>
              </li>
            <li class="nav-item active">
                <a class="nav-link" href="{{route('data.index')}}">Data santé<span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>

<main role="main" class="container-fluid" style="padding-top: 5rem;">

    <div class="starter-template" style=" padding: 3rem 1.5rem;">
        @yield('content')
    </div>

</main><!-- /.container -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script type="text/javascript" language="javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>
<script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
<script src='/js/meteo.js'></script>
<script src='/js/main.js'></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $('#sorted_table').DataTable();
    } );
</script>
<script>
    $(document).ready(function() {
        $('#summernote').summernote();
    });
</script>


<script src="/js/js.js" ></script>
<script src="/js/Home.js" ></script>


</body></html>

site/resources/views/excursion.blade.php
@extends('default')
@section('title')
    Excursion
@endsection
@section('content')
    <style type="text/css">
        #map { /* la carte DOIT avoir une hauteur sinon elle n'apparaît pas */
            height: 400px;
        }
    </style>
    <div class="container">
        <div class='alert alert-info w-100 text-center content'>
        </div>
        <div class="row">

            <div class="col-10">
                <div id="all">

                    <div id="map"></div>

                </div>
            </div>
            <div class="col-2">
                <h1>Vent:</h1>
                <img src='/img/fleche.png' id='fleche'>
                <input type="button" class="btn btn-success"value="APPEL API METEO" onclick="buttonClickGET()"/><p id="zone_meteo">Météo non initialisée</p>
                <hr>

                <details>
                    <summary>Géolocalisation :</summary>
                    <p id="long">Longitude : null</p>
                    <p id="lat">Latitude : null</p>
                </details>
                <hr>
                <button class="btn btn-primary" onclick="refresh()">Recentrer</button>
            </div>
        </div>
    </div>

    <script>
        var botmanWidget = {
            frameEndpoint: 'chatbot/chat.html',
            introMessage: 'Bonjour, je suis votre compagnon de voyage',
            chatServer : 'chat.php',
            title: 'My Chatbot',
            mainColor: '#456765',
            bubbleBackground: '#ff76f4',
            aboutText: '',
            bubbleAvatarUrl: '',
        };
    </script>
    <script src='https://cdn.jsdelivr.net/npm/botman-web-widget@0/build/js/widget.js'></script>
    <script src='/js/gyronorm.js'></script>
    <script src='/js/life.js'></script>
    <script>
    init_gn();
    </script>


@endsection

site/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

site/resources/views/index.blade.php
@extends('default')

@section('content')
  <div class="'w-100 h-100" style="position:relative">

    <a id="HomeDesert2" href="{{ route('menu') }}" > <h1> Entrer </h1> </a>

    <div class="HomeDesert" style="position:absolute"> </div>

  </div>

@endsection

site/resources/views/menu.blade.php
@extends('default')
@section('content')
<div class="container">
      <div class="row">
          <a class="col-3 square d-flex nolink" href="{{route('tableau-de-bord')}}">
              <div class='w-100 text-center m-0 p-1 d-flex align-items-center justify-content-center bg-theme5'>
                  <h2>Tableau de bord</h2>
              </div>
          </a>
          <a class="col-3 square d-flex nolink" href="{{route('equipement.index')}}">
              <div class='w-100 text-center m-0 p-1 d-flex align-items-center justify-content-center bg-theme5'>
                  <h2>Equipement</h2>
              </div>
          </a>
          <a class="col-3 square d-flex nolink" href="{{route('data.index')}}">
              <div class='w-100 text-center m-0 p-1 d-flex align-items-center justify-content-center bg-theme5'>
                  <h2>Gérer les signaux vitaux</h2>
              </div>
          </a>
            <a class="col-3 square d-flex nolink" href="{{route('excursion')}}">
                <div class='w-100 text-center m-0 p-1 d-flex align-items-center justify-content-center bg-theme5'>
                  <h2>Aller en expédition</h2>
              </div>
            </a>
      </div>
    <div class="row">
        <a href="{{route('stocks.list')}}" class="btn btn-primary">Vérifier les stocks</a>
    </div>
</div>
@endsection

site/resources/views/tableau-de-bord.blade.php
@extends('default')
@section('content')
<div class="container">
      <div class="row">
          <a class="col square d-flex nolink" href="{{route('planning.index')}}">
              <div class='w-100 text-center m-0 p-1 d-flex align-items-center justify-content-center bg-theme1'>
                  <h2>Planning</h2>
              </div>
          </a>
          <a class="col square d-flex nolink" href="{{route('todo-list.index')}}">
              <div class='w-100 text-center m-0 p-1 d-flex align-items-center justify-content-center bg-theme5'>
                  <h2>Préparer une expédition</h2>
              </div>
          </a>
          <a class="col square d-flex nolink" href="{{route('todo-list.index')}}">
              <div class='w-100 text-center m-0 p-1 d-flex align-items-center justify-content-center bg-theme3'>
                  <h2>Opérations et protocoles</h2>
              </div>
          </a>
      </div>
</div>
@endsection