site/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('root');

Route::get('/excursion', function () {
    return view('excursion');
})->name('excursion');

Route::get('/menu', function () {
    return view('menu');
})->name('menu');

Route::get('stocks/list','StockController@list')->name('stocks.list');
Route::resource('stocks', 'StockController');
Route::get('equipement/list','EquipementController@list')->name('equipement.list');
Route::resource('equipement', 'EquipementController');
Route::get('tableau-de-bord', 'TableauDeBordController@afficher')->name('tableau-de-bord');
Route::resource('tasks', 'TasksController');
Route::resource('todo-list', 'TodoListController');
Route::resource('types', 'TypeController');
Route::resource('planning', 'PlanningController');
Route::resource('data','DataController');

Route::get('/home', 'HomeController@index')->name('home');

site/app/Equipement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Equipement extends Model
{
    protected $table = "equipements";
    protected $primaryKey = "id";
}

site/app/Http/Controllers/EquipementController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Equipement;

class EquipementController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $equipements = Equipement::all();
        return view("equipements.index", compact("equipements"));
    }
    public function list()
    {
        $equipements = Equipement::all();
        return view("equipements.list", compact("equipements"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("equipements.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            "name" => "required|string|min:5|max:255",
            "type" => ["required", Rule::in([Equipement::$types])]
        ]);

        $e = new Equipement();
        $e->name = $data->name;
        $e->type = $data->type;
        $e->save();

        return redirect()->route("equipements.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(int $id)
    {
        $equip = Equipement::find($id);
        return view("equipements.show", compact("equip"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $equipement = Equipement::find($id);
        return view("equipements.edit", compact("equipement"));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->validate([
            "carac" => "string",
        ]);

        $e = Equipement::find($id);

        $e->carac = $data['carac'];

        $e->save();
        $equipements = Equipement::all();
        return view("equipements.list", compact("equipements"));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $e = Equipement::find($id);
        $e->delete();
        return redirect()->route("equipements.index");
    }
}

site/resources/views/equipements/create.blade.php
@extends('default')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card card-default">
        <div class="card-header">Nouvel équipement</div>
        <div class="card-body">

            <form action="{{route('equipement.store')}}" method="POST">
                {{csrf_field()}}
                <div class="form-group">

                    <div class="col-md-6">
                        <label for="name" class='col-md-4 control-label'>Nom</label>
                        <input type="text" class="form-control" id="name" name="name">
                    </div>
                    <div class="col-md-6">
                        <label for="carac" class='col-md-4 control-label'>Caractéristique</label>
                        <input type="text" class="form-control" id="carac" name="carac">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">
                            Nouvel équipement
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>


@endsection

site/resources/views/equipements/edit.blade.php
@extends('default')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card card-default">
        <div class="card-header">Modifier l'équipement</div>
        <div class="card-body">

            <form action="{{route('equipement.update', $equipement->id)}}" method="POST">
                @method('PUT')
                @csrf
                <div class="form-group">

                    <div class="col-md-6">
                        <label for="name" class='col-md-4 control-label'>Nom</label>
                        <input type="text" class="form-control" id="name" name="name" value="{{$equipement->name}}" disabled>
                    </div>
                    <div class="col-md-6">
                        <label for="carac" class='col-md-4 control-label'>Caractéristique</label>
                        <input type="text" class="form-control" id="carac" name="carac" value="{{$equipement->carac}}">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">
                            Modifier l'équipement
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>


@endsection

site/resources/views/equipements/index.blade.php
@extends('default')
@section('content')
<script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script>
<script src="/js/equipements.js"></script>
<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <h1> Equipements </h1>
            <div class="accordion" id="accordionExample">
            @foreach($equipements as $var)
                <div class="card">
                <div class="card-header" id="{{$var['id']}}">
                  <h5 class="mb-0">
                    <button id ="{{$var['type']}}" class="btn btn-link collapsed text-body" type="button" data-toggle="collapse" data-target={{"#collapse".$var['id']}} aria-expanded="true" aria-controls="collapseOne">
                       {{$var['name']}}
                    </button>
                  </h5>
                </div>
                <div id={{"collapse".$var['id']}} class="collapse text-left " aria-labelledby="" data-parent="#accordionExample">
                  <div class="card-body">
                    <p>Dernière vérification  {{\Carbon\Carbon::parse($var['updated_at'])->format("\l\\e d/m/Y à H:i:s")}}</p>
                      @if($var['carac'])
                        <p>Batterie : {{$var['carac']}}</p>
                      @endif
                  </div>
                </div>
              </div>
            @endforeach
            </div>
        </div>
        <div class="col-lg-6">
            <h1> Aperçu </h1>
            <img id ="aperc" src="/img/Bonhomme.png">
        </div>
    </div>
</div>
@endsection

site/resources/views/equipements/list.blade.php
@extends('default')
@section("title")
    Liste des équipements
@endsection

@section('content')
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-shopping-cart"></i>
            Gérer les équipements</div>
        <div class="card-body">
            <table id="sorted_table" class="table table-striped">
                <thead>
                <th>Nom</th>
                <th>Dernière vérification</th>
                <th>Caractéristique</th>
                <th>Type</th>
                <th>Actions</th>
                </thead>
                <tbody>
                @foreach($equipements as $equipement)
                    <tr style="text-align: center">
                        <td>{{{$equipement->name}}}</td>
                        <td>{{$equipement->updated_at}}</td>
                        <td>{{$equipement->carac}}</td>
                        <td>{{$equipement->type}}</td>
                        <td><a href="{{{ route('equipement.edit', $equipement) }}}" class="btn btn-primary">Editer</a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>

        </div>
        <div class="card-footer"><a href="{{ route('equipement.create') }}" class="btn btn-success">Nouveau</a></div>
    </div>

@endsection