site/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('root');

Route::get('/excursion', function () {
    return view('excursion');
})->name('excursion');

Route::get('/menu', function () {
    return view('menu');
})->name('menu');

Route::get('stocks/list','StockController@list')->name('stocks.list');
Route::resource('stocks', 'StockController');
Route::get('equipement/list','EquipementController@list')->name('equipement.list');
Route::resource('equipement', 'EquipementController');
Route::get('tableau-de-bord', 'TableauDeBordController@afficher')->name('tableau-de-bord');
Route::resource('tasks', 'TasksController');
Route::resource('todo-list', 'TodoListController');
Route::resource('types', 'TypeController');
Route::resource('planning', 'PlanningController');
Route::resource('data','DataController');

Route::get('/home', 'HomeController@index')->name('home');

site/app/Planning.php
<?php

namespace App;
use Illuminate\Database\Eloquent\Model;

class Planning extends Model
{
    protected $table = "planning";
    protected $primaryKey="id";
}

site/app/Http/Controllers/PlanningController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Planning;
use App\Todo_list;

class PlanningController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $plannings=Planning::all();
        return view('planning.index',compact('plannings'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tdls=Todo_list::all();
        return view('planning.create',compact('tdls'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'horaire' => 'required|Time',
            'id_todo' => 'required|Integer'
        ]);

        $plan = new Planning();
        $plan->horaire = $request->horaire;
        $plan->id_todo = $request->id_todo;

        $mess=$plan->save() ? "successfull saving in database":"fail to save in database";

        $request->session()->flash("mess", $mess);

        return redirect()->route('planning.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $planning=Planning::find($id);
        return view('planning.show',compact('planning'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $planning=Planning::find($id);
        return view('planning.edit',compact('planning'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $result=$request->validate([
            'horaire' => 'required|Time',
            'id_todo' => 'required|Integer'
        ]);

        $plan=Planning::find($id);

        if(isset($result->weight))
            $plan->horaire=$result->horaire;
        if(isset($result->height))
            $plan->id_todo=$result->id_todo;

        $plan->save();
        return view(route('planning.show',['id'=>$id]));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $planning=Planning::find($id);
        $mess=$planning->delete() ? "successfull suppressing":"fail in suppressing resource";
        $request->session()->flash('mess',$mess );
        return redirect()->route('data.index');
    }
}

site/resources/views/planning/create.blade.php
@extends('default')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card card-default">
        <div class="card-header">Nouveau planning</div>
        <div class="card-body">

            <form action="{{route('planning.store')}}" method="POST">
                {{csrf_field()}}
                <div class="form-group">

                    <div class="col-md-6">
                        <label for="horaire" class='col-md-4 control-label'>Horaire</label>
                        <input type="time" class="form-control" id="task_title" name="task_title">
                    </div>
                    <div class="col-md-6">
                        <label for="id_todo" class='col-md-4 control-label'>Todo-List</label>
                        <select class="form-control" id="id_todo" name="id_todo">
                            @foreach($tdls as $tdl)
                            <option value="{{$tdl->id}}">{{$tdl->title}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">
                            Nouveau Planning
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>


@endsection

site/resources/views/planning/edit.blade.php
@extends('default')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card card-default">
        <div class="card-header">Nouveau Planning</div>
        <div class="card-body">

            <form action="{{route('planning.update', $planning->id)}}" method="POST">
                @method('PUT')
                @csrf
                <div class="form-group">
                    <div class="col-md-6">
                        <label for="horaire" class='col-md-4 control-label'>Horaire</label>
                        <input type="time" class="form-control" id="task_title" name="task_title" value="">
                    </div>
                    <div class="col-md-6">
                        <label for="id_todo" class='col-md-4 control-label'>Todo-List</label>
                        <select class="form-control" id="id_todo" name="id_todo">
                            @foreach($tdl as $td)
                                <option value="{{ $td->id }}" selected>{{$td->title}}</option>
                            @endforeach
                        </select>
                    </div>
                    
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">
                            Nouveau Planning
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>


@endsection

site/resources/views/planning/index.blade.php
@extends('default')

@section('content')
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-tasks"></i>
            Gérer les stocks</div>
        <div class="card-body">
            <table id="sorted_table" class="table table-striped">
                <thead>
                <th>Horaire</th>
                <th>Todo-List</th>
                </thead>
                <tbody>
                @foreach($plannings as $plan)
                    <tr>
                        <td>{{{$plan->horaire}}}</td>
                        <td>{{$plan->id_todo}}</td>
                        <td>
                            <a href="{{{ route('planning.edit', $plan) }}}" class="btn btn-primary">Editer</a>
                            <a href="{{{ route('planning.edit', $plan) }}}" class="btn btn-primary">Afficher</a>
                            <form action="{{{ route('planning.destroy', $plan) }}}" method="post">
                                @csrf
                                {{ method_field('delete') }}
                                <button class="btn btn-danger" type="submit">Supprimer</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

        </div>
        <div class="card-footer"><a href="{{ route('planning.create') }}" class="btn btn-success">Nouveau</a></div>
    </div>

@endsection