site/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('root');

Route::get('/excursion', function () {
    return view('excursion');
})->name('excursion');

Route::get('/menu', function () {
    return view('menu');
})->name('menu');

Route::get('stocks/list','StockController@list')->name('stocks.list');
Route::resource('stocks', 'StockController');
Route::get('equipement/list','EquipementController@list')->name('equipement.list');
Route::resource('equipement', 'EquipementController');
Route::get('tableau-de-bord', 'TableauDeBordController@afficher')->name('tableau-de-bord');
Route::resource('tasks', 'TasksController');
Route::resource('todo-list', 'TodoListController');
Route::resource('types', 'TypeController');
Route::resource('planning', 'PlanningController');
Route::resource('data','DataController');

Route::get('/home', 'HomeController@index')->name('home');

site/app/Todo_list.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Todo_list extends Model
{
    protected $table = "todo_lists";
    protected $primaryKey = "id";

    public function tasks(){
    	return $this->hasMany('App\Tasks', 'id_todo');
    }

    public function plannings(){
    	return $this->hasMany('App\Planning');
    }
}

site/app/Http/Controllers/TodoListController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Todo_list;

class TodoListController extends Controller
{

    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tdl = Todo_list::all();
        $colors = ['theme1', 'theme2', 'theme3', "theme4", 'theme5'];
        foreach($tdl as $td)
        {
            $td["color"] = $colors[array_rand($colors)];
        }
        return view("todoList.index", compact("tdl"));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("todoList.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|String',
            'check' => 'filled',
        ]);

        $tdl = new Todo_list();
        $tdl->title = $request->title;

        if(isset($request->check)){
            $tdl->checked = true;
        } else {
            $tdl->checked = false;
        }

        $tdl->save();

        $request->session()->flash('msg', 'L\'élément a bien été ajouté !');


        return redirect()->route("todo-list.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $tdl = Todo_list::find($id);

        return view("todoList.show", compact('tdl'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tdl = Todo_list::find($id);

        return view("todoList.edit", compact('tdl'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'String',
            'check' => 'filled',
        ]);

        $tdl = Todo_list::find($id);
        if (isset($request->title))
            $tdl->title = $request->title;

        if(isset($request->check)){
            $tdl->checked = true;
        } else {
            $tdl->checked = false;
        }

        $tdl->save();


        $request->session()->flash('msg', 'L\'élément a bien été modifié !');

        return redirect()->route("todo-list.index");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $tdl = Todo_list::find($id);
        $tdl->delete();

        $request->session()->flash('msg', 'L\'élément a bien été supprimé !');

        return redirect()->route("todo-list.index");
    }
}

site/resources/views/todoList/create.blade.php
@extends('default')

@section('content')
    @if ($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="card card-default">
        <div class="card-header">Créer une Todo-list</div>
        <div class="card-body">

            <form action="{{route('todo-list.store')}}" method="POST">
                {{csrf_field()}}
                <div class="form-group">

                    <div class="col-md-6">
                        <label for="name" class='col-md-4 control-label'>Titre</label>
                        <input type="text" class="form-control" id="title" name="title">
                    </div>
                    <div class="col-md-6">
                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="materialChecked2" name="check">
                            <label class="form-check-label" for="materialChecked2">Effectué</label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">Nouvelle Todo-list</button>
                    </div>
                </div>
            </form>
        </div>
    </div>


@endsection

site/resources/views/todoList/edit.blade.php
@extends('default')

@section('content')
    <h1>Editer</h1>

    <div class="card card-default">
        <div class="card-header">Modifier une Todo-list</div>
        <div class="card-body">

            <form action="{{route('todo-list.update', ['id' => $tdl->id])}}" method="POST">
                @csrf
                @method('PUT')
                
                <div class="form-group">

                    <div class="col-md-6">
                        <label for="name" class='col-md-4 control-label'>Titre</label>
                        <input type="text" class="form-control" id="title" name="title" value="{{$tdl->title}}">
                    </div>
                    <div class="col-md-6">
                        <div class="form-check">
                            
                            @if ($tdl->checked == 1)
                            <input type="checkbox" class="form-check-input" id="materialChecked2" name="check" checked="checked">
                            @else
                            <input type="checkbox" class="form-check-input" id="materialChecked2" name="check">
                            @endif
                            <label class="form-check-label" for="materialChecked2 checked">Effectué</label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-6 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">Modifier</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

site/resources/views/todoList/index.admin.blade.php
@extends('default')

@section('content')
    <div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-list-ul"></i>
            Gérer les Todo-list</div>
        <div class="card-body">
            <table id="sorted_table" class="table table-striped">
                <thead>
                <th>Nom</th>
                <th>Fini ?</th>
                <th>Actions</th>
                </thead>
                <tbody>
                @foreach($tdl as $td)
                    <tr>
                        <td>{{{$td->title}}}</td>
                        <td>@if($td->checked)
                                <i class="fas fa-check"></i>
                            @else
                                <i class="fas fa-times"></i>
                            @endif
                        </td>
                        <td>
                            <a href="{{{ route('todo-list.edit', $td) }}}" class="btn btn-primary">Editer</a>
                            <a href="{{{ route('todo-list.show', $td) }}}" class="btn btn-primary">Afficher</a>
                            <form action="{{{ route('todo-list.destroy', $td) }}}" method="post">
                                @csrf
                                {{ method_field('delete') }}
                                <button class="btn btn-danger" type="submit">Supprimer</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

        </div>
        <div class="card-footer"><a href="{{ route('todo-list.create') }}" class="btn btn-success">Nouveau</a></div>
    </div>

@endsection

site/resources/views/todoList/index.blade.php
@extends('default')

@section('content')
    <h1 class="text-center mb-4">Résumé de toutes les opérations et protocoles disponibles</h1>

    <div class="row">
        @foreach ($tdl as $td)
            <div class='col-6 col-md-3 square d-flex p-1'>
                <a href='{{ route('todo-list.show', ['id' => $td->id]) }}' class='w-100 text-center m-0 p-1 d-flex align-items-center justify-content-center bg-{{$td->color}} nolink'>
                    <h3>{{$td->title}}</h3>
                </a>
            </div>
        @endforeach
    </div>
@endsection

site/resources/views/todoList/show.blade.php
@extends('default')

@section('content')
    <div class='container'>
        <h1 class="text-center mb-4">Opération {{ $tdl->title }}</h1>

        <div class='row'>
            <ol class='w-100 m-0'>
                @foreach($tdl->tasks()->get() as $task)
                    <li class ='mb-4'>
                        <div class='col-12 row'>
                            <div class='col-9'>
                                <h3>{{$task->task_title}}</h3>
                                <button class="btn btn-sm btn-outline-secondary mx-5 my-2" type="button" data-toggle="collapse" data-target="#desc-{{$task->id}}">
                                Afficher plus
                                  </button>
                                <div class="collapse" id="desc-{{$task->id}}">
                                  <div class="card card-body">{{$task->description}}</div>
                                </div>
                            </div>
                            <div class='col-3'>
                                <input type="checkbox" class="form-check-input checkbox-task" data-id="{{$task->id}}" name="check" {{ $task->checked ? " checked" : ""}}>
                            </div>
                        </div >
                    </li>
                @endforeach
            </ol>
        </div>
    </div>
@endsection